### ISSUE TITLE
Redirect to Success Page not work

### ISSUE THREAD

**Issue by kossanah** [ibrahimlawal/magento2-Profibro_Paystack#6]
I have tested this gateway on my Magento 2.1.1.  using several templates including Magento/Luma templates.
After submitting payment information and payment success, customer is not redirected to order success page.

**Comment by Matt-OBell** [comment]
Which http server are you using, something like that do happened with nginx server.

**Comment by AwoyoToyin** [comment]
@kossanah do you still have this issue? If yes, I just fixed it and you can find a forked repo in my profile. You can use that until @ibrahimlawal approves/merges my pull request :)

**Comment by kossanah** [comment]
@AwoyoToyin Ok I will test and revert

**Comment by AwoyoToyin** [comment]
Okay @kossanah 
One more thing, the way this works currently, I believe is problematic. The customers make payment before the order is actually placed. I strongly believe it should be the other way round.

**Comment by kossanah** [comment]
Failed to load resource: the server responded with a status of 400 (Bad Request)
/rest/default/V1/carts/mine/payment-information

why is "default" used?
http://devdocs.magento.com/swagger/#!/checkoutPaymentInformationManagementV1

I suppose the M2 api is "http://magento.com/rest/V1/" where magento.com is the site address

**Comment by zainobf** [comment]
tested in magento 2.1.6 with the 0.9.16, it still does not redirect to success page and shows "Error, please try again" after transaction. Note that test payment sends payment confirmation email despite issue. Cart treats item as items waiting for checkout in cart.

**Comment by steveamaza** [comment]
@kossanah did you resolve the error you had with @AwoyoToyin's fix? This issue apparently still persists

**Comment by kossanah** [comment]
@steveamaza Its fixed now

**Comment by alan-qbasic** [comment]
@steveamaza please can you give a some details on the fix.
Thank You.

**Comment by steveamaza** [comment]
@alan-qbasic you will have to ask @kossanah or @AwoyoToyin. I am yet to test at the moment.

**Comment by steveamaza** [comment]
Hello @kossanah can you fill me in on how you fixed this or what release version you used to fix this? I am still having these errors. Like @alan-qbasic asked, can you give some details?

**Comment by ibrahimlawal** [comment]
@alan-qbasic are you certain this issue is unresolved for you? Kindly provide these information in a new thread:

1. Your exact Magento 2 version
2. The exact version of the Plugin you are using (latest is 0.9.16)
3. The PHP version on your server
4. Any staging server at which we can duplicate
5. Any screenshots to describe the issue.

Thank you for choosing Paystack.

Thanks!

**Comment by ibrahimlawal** [comment]
Oh, and just a note:

We had checked @zainobf 's installation after her post above and we realized it wasn't fixed for her because of cache and minification issues. After rebuilding the cache, it was sorted, @alan-qbasic . We just forgot to post the outcome afterwards.

**Comment by steveamaza** [comment]
Here is an integration with this issue.

1. Magento 2.1.9
2: I installed the 0.9.16 version as well
3: PHP 5.6.30
4. http://bookmia.com/

**Comment by alan-qbasic** [comment]
@ibrahimlawal 

1. Magento ver. 1.9.2.4
2.  <name>Paystack_Inline</name><version>1.0.0.1</version>
3. PHP Version 5.6.30
4. http://104.197.114.217/havilah/
![capture](https://user-images.githubusercontent.com/29778801/32714522-918eaf12-c84e-11e7-90b2-c4f0872eb44a.PNG)

That is what i get even after a successful transaction.

Thanks!

**Comment by abbeyseto** [comment]
Hello, i'm sorry i had to comment on this issue. I still have a problem redirecting to success page while testing. After a payment, i see A transaction successful pop up and it disappears but the page page remains the same. It is not redirected to success page.

Magento ver. 2.26
Paystack: Magento2.1 plugin (installed using composer)
PHP Version: 7.1
Server: Linux on Google Compute engine

**Comment by steveamaza** [comment]
Please provide a link so one can test

**Comment by abbeyseto** [comment]
> Please provide a link so one can test
> […](#)
> On Oct 15, 2018, 8:52 PM +0100, Adenle Abiodun ***@***.***>, wrote: Hello, i'm sorry i had to comment on this issue. I still have a problem redirecting to success page while testing. After a payment, i see A transaction successful pop up and it disappears but the page page remains the same. It is not redirected to success page. Magento ver. 2.26 Paystack: Magento2.1 plugin (installed using composer) PHP Version: 7.1 Server: Linux on Google Compute engine — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

@steveamaza the link is http://35.225.81.135/ 

N.B you might get warnings that site not safe, its because i'm don't have SSL cert for the IP address.

Thank you.

**Comment by abbeyseto** [comment]
hello @steveamaza , How are you? i want to remind you about the issue i indicated above, about *"page not redirected to success page"*. I notice you have tested it. Kindly let me hear your feedback about this. Is there a way i can rectify this behavior?.

**Comment by steveamaza** [comment]
Hello @abbeyseto this is likely because your server is not configured for TLS 1.2 connections. Please email us at support@paystack.com so we can test this.

**Comment by sheyinn** [comment]
Hello,

Having the same issue. Getting a 400 (bad request) response after successful test payment. Can someone please share a working fix here?

**Comment by steveamaza** [comment]
@coldasiyce what is the exact version of Magento you are using?

**Comment by sheyinn** [comment]
Version 2.2.6 installed via my cpanel

Sent from my Windows 10 device

**Comment by steveamaza** [comment]
@coldasiyce, version 2.2.6 is not yet available. We are currently working on it cc @femialuko

**Comment by sheyinn** [comment]
Okay @steveamaza , what version is currently available? I might have to downgrade my Magento version due to the urgency of my project.

**Comment by steveamaza** [comment]
Hey Sheyin, it's compatible with Magento 2.2.5 and below.

**Comment by sheunl** [comment]
Hello, I am using Magento ver. 2.2.6 and the checkout page is not redirecting to success page after completing payment. What is the solution?

**Comment by steveamaza** [comment]
@thetechtitan, this is a compatibility issue with 2.2.6. I have opened a separate issue for it at #26 so please watch it to know when this has been fixed.

**Comment by steveamaza** [comment]
@thetechtitan @sheyinn the extension has now been updated for 2.2.6. Please reinstall and test
